### ISSUE TITLE
Move ping to Bridge server

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/node-walletconnect-bridge#28]
Requires WalletConnect/walletconnect-monorepo#139

**Comment by rmeissner** [comment]
It seems that https://github.com/WalletConnect/node-walletconnect-bridge/pull/33 implements this, but this breaks clients (since "ping" is not a valid method). I would strongly recommend reverting this PR.

Also the `ping` should not be a message. It is a special request (see https://tools.ietf.org/html/rfc6455#section-5.5.2)

**Comment by pedrouid** [comment]
Hi @rmeissner, you're right and I'm currently working on it right now. A fixed will be published today for both client and server repos
